/** Semantic roles from Redesign 2026. Legacy keys keep existing screens compatible. */
import { colorTokens, primitiveTokens } from './token-manager.js';

function semantic(c: typeof colorTokens.Light) {
  return {
    bgCanvas: c['bg/canvas'],
    bgSurface: c['bg/surface'],
    bgSurfaceAlt: c['bg/surface-alt'],
    bgSubtle: c['bg/surface-alt'],
    bgInset: c['border/subtle'],
    bgInverse: c['bg/inverse'],
    bgElevated: c['bg/elevated'],
    inkStrong: c['ink/strong'],
    inkDefault: c['ink/body'],
    inkMuted: c['ink/muted'],
    inkFaint: c['ink/muted'],
    inkInverse: c['ink/inverse'],
    inkOnAccent: c['ink/on-accent'],
    inkOnElevated: c['ink/on-elevated'],
    inkOnElevatedMuted: c['ink/on-elevated-muted'],
    brandAccent: c['brand/accent'],
    brandAccentHover: c['brand/accent-hover'],
    brandAccentSubtle: c['brand/accent-subtle'],
    brandAccentText: c['brand/accent-text'],
    brandAccentOnElevated: c['brand/accent-on-elevated'],
    brandAccentOnInverse: c['brand/accent-on-inverse'],
    brandSplashEnd: c['brand/splash-end'],
    borderDefault: c['border/subtle'],
    borderStrong: c['border/strong'],
    borderControl: c['border/control'],
    borderFocus: c['border/focus'],
    statusSuccess: c['status/success'],
    statusSuccessTint: c['status/success-bg'],
    statusWarning: c['status/warning'],
    statusWarningTint: c['status/warning-bg'],
    statusDanger: c['status/danger'],
    statusDangerTint: c['status/danger-bg'],
    statusInfo: c['status/info'],
    statusInfoTint: c['status/info-bg'],
    statusDangerOnElevated: c['status/danger-on-elevated'],
    moneyAvailable: c['money/available'],
    moneyHeld: c['money/held'],
    moneyPending: c['money/pending'],
    moneyHeldOnElevated: c['money/held-on-elevated'],
    moneyHeldOnInverse: c['money/held-on-inverse'],
    actionPrimaryPressed: c['action/primary-pressed'],
    actionDangerPressed: c['action/danger-pressed'],
    actionDisabled: c['action/disabled'],
    inkOnDanger: primitiveTokens['neutral/0'],
    // Older screen names map to semantic roles, never to the retired emerald palette.
    inverseInk: c['ink/on-elevated'],
    brandSurface: c['bg/elevated'],
    dangerSurface: primitiveTokens['red/600'],
    onBrandAccent: c['brand/accent-on-elevated'],
    brandEmerald: c['brand/accent-text'],
    brandEmeraldStrong: c['brand/accent-text'],
    brandEmeraldTint: c['brand/accent-subtle'],
    brandEmeraldTintWeak: c['brand/accent-subtle'],
    accentGold: c['money/held-on-elevated'],
    accentGoldStrong: c['money/held'],
    accentGoldTint: c['status/warning-bg'],
    statusHeld: c['money/held'],
    overlay: 'rgba(0, 0, 0, 0.6)',
    transparent: 'transparent',
  };
}
export const lightColors = semantic(colorTokens.Light);
export type SemanticColors = Record<keyof typeof lightColors, string>;
export const darkColors: SemanticColors = semantic(colorTokens.Dark);
